version: "3.8"

volumes:
  redis_data:
  mariadb_data:
  pg_data:
  influxdb_data:
  victoria-metrics-data:

services:
  # https://hub.docker.com/_/mariadb
  mariadb:
    image: mirror.gcr.io/mariadb:10.11.6
    environment:
      MYSQL_ROOT_PASSWORD: "dashboard"
      MYSQL_DATABASE: "dashboard"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # https://hub.docker.com/_/postgres
  postgres:
    image: mirror.gcr.io/postgres:15-alpine
    environment:
      POSTGRES_USER: "dashboard"
      POSTGRES_PASSWORD: "dashboard"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # https://hub.docker.com/_/redis
  redis:
    image: mirror.gcr.io/redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # https://hub.docker.com/_/influxdb
  influx:
    image: mirror.gcr.io/influxdb:2-alpine
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "dashboard"
      DOCKER_INFLUXDB_INIT_PASSWORD: "dashboard"
      DOCKER_INFLUXDB_INIT_ORG: "dashboard"
      DOCKER_INFLUXDB_INIT_BUCKET: "dashboard"
      DOCKER_INFLUXDB_INIT_RETENTION: "1d"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "-l3Y5tIHGJAxXv_Rs5kJ4kAfPbgmf3WPmFUTDuKmD3Z9gp29E7e188-dIt5MAKhSTzv1J6v_pkPuVdIbXqdL1w=="
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # https://hub.docker.com/r/victoriametrics/victoria-metrics
  victoria:
    image: mirror.gcr.io/victoriametrics/victoria-metrics:v1.118.0-scratch
    ports:
      - "8428:8428"
    volumes:
      - victoria-metrics-data:/victoria-metrics-data

  dashboard:
    build:
      context: ./
      dockerfile: ./Dockerfile_development
    ports:
      - "3001:3001"
    volumes:
      - ./contrib/dashboard_docker.yaml:/etc/dashboard.yaml:Z,U
      - ./contrib/header.html:/etc/header.html:Z,U
      - ./contrib/footer.html:/etc/footer.html:Z,U
